services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-2
    hostname: rabbitmq-2
    entrypoint: ["/entrypoint-node2.sh"]
    ports:
      - "5000:5672"
      - "15672:15672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbitmq-2
      RABBITMQ_ERLANG_COOKIE: CLUSTER_SECRET_COOKIE_123
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin_password
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq
      - ./certs:/certs:ro
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/20-ssl.conf:ro
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  rabbitmq2_data:
